### ISSUE TITLE
VDM auth: create OIDC client

### ISSUE THREAD

**Issue by soxofaan** [WorldCereal/worldcereal-vdm#9]
spin off from #8 :

Create a VDM specific OIDC client in CDSE Keycloak (both staging and prod) to be used with auth code flow.

If useful I could also set it up on Terrascope Keycloak (which could go quicker than the CDSE procedures) for development purposes

**Comment by soxofaan** [comment]
@mbabic84 

What I need from VDM devs to set this up is at least (assuming this client will only be about auth code flow, I'm also assuming you're familiar with the OIDC related terminology involved here, if not: feel free to ask):

- all redirect URI that must be allow-listed (including "localhost" ones if necessary for development purposes)
- (usually the redirect URIs imply this, but just to be sure:) all domains that should be CORS-allow-listed (including localhost if necessary)

as discussed, let's start with the dev/staging use case to first iron all the kinks out  and care about the perfect production setup later

**Comment by soxofaan** [comment]
minor status update from the VDM dev team (per email Aug 29):

> there is still no progress from our side. We still have some issues on our side, which needs to be taken care of first, before we are able to communicate all necessary information mentioned in the issue.

**Comment by mbabic84** [comment]
@soxofaan Hello again and sorry it took too long to get back to you. Right now, we have public dev domain, which is "worldcerealprocesses-dev.gisat.cz" and also we usually use "localhost:3000" for local development. Callback url is "/api/auth/callback".

On latest meet, we agreed to use only OICD on Terrascope for now.

Is there anything else we should specify?

Can you provide us with following?

CLIENT_ID
OID_IAM_ISSUER_URL
OID_IAM_AUTHORIZE_URL
OID_IAM_TOKEN_URL

Thank you,

Martin

**Comment by soxofaan** [comment]
I added the entry to our keycloak config system. I'm now waiting for the prod deploy

**Comment by soxofaan** [comment]
the account is working, I'll send you the credentials with a secret note

**Comment by mbabic84** [comment]
@soxofaan Thank you for credentials. We are trying to set it up on our side, but right now, we are getting following error when we try to call Terrascope with "https://sso.terrascope.be/auth/realms/terrascope/protocol/openid-connect/auth?client_id=openeo-worldcereal-vdm-service-account&scope=email&response_type=code&redirect_uri=https%3A%2F%2Fworldcerealprocesses-dev.gisat.cz%2Fapi%2Fauth%2Fcallback"

query params:
  client_id: openeo-worldcereal-vdm-service-account
  scope: email
  response_type: code
  redirect_uri: https://worldcerealprocesses-dev.gisat.cz/api/auth/callback

![image](https://github.com/user-attachments/assets/1f104852-617e-4355-9a3e-b2271dffabd0)

**Comment by soxofaan** [comment]
ouch apologies,  I created a OIDC client with client credentials grant instead of auth code grant, I'll have to change that

**Comment by soxofaan** [comment]
sent updated instructions
